[package]
name = "smartdiff"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version= "0.13.1", features = ["canvas"] }
clap = { version = "4.5.39", features = ["derive"] }
git2 = "0.20.2"
anyhow = "1.0.98"
glob = "0.3.2"
log = "0.4.27"
env_logger = "0.11.8"
