on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz
          - target: x86_64-pc-windows-gnu
            archive: zip
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      - name: Compile and release
        uses: ./ci/rust-build.action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_TOOLCHAIN: 1.87.0
          BINARIES: "smartdiff"
        with:
          RUSTTARGET: ${{ matrix.target }}
